accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import TaskCreateView, TaskListView, TaskUpdateView, task_search

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("search/", task_search, name="search"),
    # path("<int:pk>/edit/", TaskUpdateView.as_view(), name="update_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("", RedirectView.as_view(url=reverse_lazy("create_task"))),
]

accounts/models.py
# from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name


# Create your models here.

tasks/models.py
from django.db import models
from django.conf import settings
from projects.models import Project

USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, related_name="tasks", null=True, on_delete=models.SET_NULL
    )
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")

        else:
            form = UserCreationForm()
            context = {
                "form": form,
            }
            return render(request, "registration/signup.html", context)
    else:
        form = UserCreationForm()
        context = {
            "form": form,
        }
        return render(request, "registration/signup.html", context)


# Create your views here.

projects/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# from django.shortcuts import render, redirect


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ["name", "description", "members"]
    template_name = "create.html"

    def get_success_url(self):
        # return reverse_lazy("show_project", kwargs={"pk": self.object.pk})
        return reverse_lazy("show_project", args=[self.object.id])

# Create your views here.

tasks/views.py
from tasks.models import Task
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.shortcuts import render


def task_search(request):
    if request.method == "POST":
        searched = request.POST.get('searched')
        tasks = Task.objects.filter(name__icontains=searched)
        return render(request, "search.html", {'searched':searched, 'tasks':tasks})
    else:
        return render(request, "search.html", {})
    

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["name", "start_date", "due_date", "project", "assignee", "notes"]
    template_name = "tasks_create.html"

    def get_success_url(self):
        return reverse_lazy(
            "show_project", args=[self.object.project.pk]
        )
        return reverse_lazy(
            "show_project", kwargs={"pk": self.object.project.pk}
        )

class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks_list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["name", "due_date", "is_completed", "notes"]
    template_name = "tasks_update.html"
    success_url = reverse_lazy("show_my_tasks")


# Create your views here.

accounts/templates/base.html
{% load static %} <!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <div class="dropdown">
                        <button class="project_dropdown_btn">Projects</button>
                            <div class="dropdown-content">
                                <a href="{% url 'list_projects'%}">Project list</a>
                                <a href="{% url 'create_project'%}">Create a project</a>
                            </div>
                        {% comment %} <a href="{% url 'list_projects'%}">My projects</a> {% endcomment %}
                    </div>
                    <div class= "nav_username">
                        Hi, {{user.username}} ❤️
                    </div>
                    <div class="task_bar">
                        
                            <a href="{% url 'show_my_tasks'%}">Assigned Tasks</a>
                    
                    </div>
                        <div class="logout_bar">
                            <a href="{% url 'logout'%}">Logout</a>
                            
                        </div>
                        <div>
                            <span class="material-symbols-outlined">
                                search
                                </span>
                             <form class= "search_form" method = "post" action="{% url 'search'%}">
                                {% csrf_token %}
                                <input type="search" placeholder="Search Tasks" name="searched">
                                <button type="submit">Search</button>
                            </form>
                        </div>
                    {% endif%}
                </ul>
            </nav>
        </header>
        {% block content%} {% endblock content %} 
    </body>
</html>

projects/templates/create.html
{%extends 'base.html' %}{% block content %} {% load static %} 
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %} {{form.as_p}} 
            </form>
            <button class="project-form-button">Create</button>
        </div>
    </main>
{% endblock content%}

projects/templates/detail.html
{% extends 'base.html' %} {% load markdownify %} {% block content%} {% load static %} 
    <main>
        <h1>{{project.name}}</h1>
            {{ project.description|markdownify }}
        <h2>Tasks</h2> 
        <a class="create" href="{% url 'create_task' %}">Create a new task</a>
        <div class="project-detail">
            {% if project.tasks.all|length == 0 %}
                <p>This project has no tasks</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                            <th>Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{task.name}}</td>
                                <td>{{task.assignee}}</td>
                                <td>{{task.start_date}}</td>
                                <td>{{task.due_date}}</td>
                                <td>{{task.is_completed|yesno}}</td>
                                <td>{% if task.notes|length > 0%}{{task.notes}}</td>
                                {%else%}
                                <p> No notes</p>
                                {%endif%}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/list.html
{% extends 'base.html' %} {% block content %} {% load static %} 
    <main>
        <h1>My Projects</h1>
        <div class="project-list">
            
            {% comment %} <p>
                <a href="{% url 'create_project'%}">Create a new project</a>
            </p> {% endcomment %}
            {% if project_list|length == 0 %}
                <p>You are not assigned to any projects</p>
            {% else %}
                <table class="table-table-striped">
                    <thead>
                        <tr class="project_list_row">
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_project' project.pk%}">{{project.name}}</a>
                                </td>
                                <td>{{project.tasks.all|length}}</td>
                            </tr>
                        {% endfor%}
                    </tbody>
                </table>
            {%endif%}
        </div>
    </main>
{% endblock content %}

tasks/templates/search.html
{% extends 'base.html'%} {% block content%}
<main>
    {% if searched %}
    <h1> You have searched for {{searched}} </h1>
    {% for task in tasks%}
    <ul>
    </li>
    {{task.project.name}}: <a href="{% url 'show_project' task.project.id%}">{{task.name}}</a>
    </li>
    </ul>
    {%endfor%} 
    {%else%} 
    <h1> You forgot to search!</h1>
    {%endif%}
</main>
{%endblock content%}

tasks/templates/tasks_create.html
{% extends 'base.html' %} {% block content%} {% load static %} 
    <main>
        <div class="task-form">
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %} {{form.as_p}} 
            </form>
            <button class="task-form-button">Create</button>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks_list.html
{% extends 'base.html' %} {% block content %} {% load static %} 
    <main>
        <h1>My Tasks</h1>
        <div class="my-tasks-list">
            
            {% if task_list|length == 0 %}
                <p>You have no tasks</p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                            <th>Notes</th>
                        
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td>{{task.name}}</td>
                                <td>{{task.start_date}}</td>
                                <td>{{task.due_date}}</td>

                                <td>
                                    {% if task.is_completed == False%}
                                        <form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True" />
                                            <p>No</p>
                                    {%else%} {{task.is_completed|yesno:"Yes,"}}
                                        </form>
                                    {%endif%}
                                </td>
                                    
                                <td>{% if task.notes|length > 0%}{{task.notes}}</td>
                                    {%else%}
                                    <p> No notes</p>
                                    {%endif%}
                               {% comment %} <td>
                                    <form method="post" action="{% url 'update_task' task.id %}">
                                        {% csrf_token %} {{form.as_p}}
                                    <button class="edit_note">Edit</button></form>
                                </td>  {% endcomment %}
                            </tr>
                        {% endfor%}
                    </tbody>
                </table>
            {%endif%}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks_update.html
{% extends 'base.html' %}{% load static %}  {% block content%} 
    <main>
        <div class="task-form">
            <h1>Update task</h1>
            <form method="post">
                {% csrf_token %} {{form.as_p}} 
               <button>Update</button>
            </form>
        </div>
    </main>
{% endblock content %}